Repository Nihongo-Jouzu/nihongo-jouzu-backend, pull requests merged in 2024-09, with the labels that each got.

#12 Database migration
  backend/api/migrations/0001_initial.py
  backend/api/models.py
  backend/api/serializers.py
  backend/api/tests.py
  backend/api/urls.py
  backend/api/views.py
  backend/backend/migrations/0001_initial.py
  backend/backend/migrations/0002_remove_wordslearned_content_remove_lobby_game_type_and_more.py
  backend/backend/settings.py
Labels: enhancement

#15 Auth from backend
  backend/api/admin.py
  backend/api/migrations/0001_initial.py
  backend/api/models.py
  backend/api/urls.py
  backend/api/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/requirements.txt
Labels: enhancement

#19 Update README.md
  README.md
Labels: documentation

#28 Try django test workflow
  .github/workflows/django.yml
Labels: enhancement

#38 34 bug cant login with fixture data
  README.md
  backend/api/fixtures/initial_data.json
  backend/api/fixtures/users.json
Labels: enhancement

#48 [FIX] Endpoint for scoreboard and words learned
  backend/api/migrations/0003_remove_score_user_score_player1_score_player2.py
  backend/api/models.py
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/entrypoint.sh
Labels: bug

#52 Fix: Create unique constraint with user and content
  backend/api/fixtures/initial_data.json
  backend/api/migrations/0005_wordslearned_user_content_squashed_0011_remove_wordslearned_user_content.py
  backend/api/models.py
  backend/api/urls.py
  backend/api/views.py
Labels: bug

#54 [BUG] Change score schema
  backend/api/migrations/0012_remove_score_game_id.py
  backend/api/migrations/0013_remove_score_player1_remove_score_player2_and_more.py
  backend/api/migrations/0014_alter_score_loser_alter_score_winner.py
  backend/api/models.py
  backend/api/serializers.py
  backend/api/views.py
  backend/entrypoint.sh
  backend/gunicorn.conf.py
Labels: bug
